eureka:
  client:
    service-url:
      defaultZone: http://${custom.eureka.host}:${custom.eureka.port}/eureka
---
spring:
  application:
    name: eureka-server-1
  profiles: eureka-1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
custom:
  eureka:
    port: 8761
    host: localhost
---
spring:
  application:
    name: eureka-server-2
  profiles: eureka-2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
custom:
  eureka:
    port: 8762
    host: localhost